immudbserver = "127.0.0.1"
immmudbport = 3322
immudbuser = "immudb"
immudbpassword = "immudb"
rcloneremote = "test"
rcloneparameter = "--s3-no-check-bucket"
agerecipientfile = "./recipient_file"
agekeyfile = "./key"